ADB:
- C:/CODE/sabel.png /sdcard/
- com.emo_framework.examples/com.emo_framework.EmoActivity
- EmoFramework
- com.emo_framework.examples
ANT:
- android update project --target 5 --path .
- ant debug install
CMD:
- GCC
- CMD
- PYTHON
- ADB
- G++
- Make
- SQ
- JAVA
ClosedProject:
- 0
- 0
File:
- C:/CODE/assets/creditscene.nut
- C:/CODE/assets/howtoscene.nut
- C:/CODE/data/runtime.nut
Project:
- C:/CODE/data/
- C:/CODE/assets/
Recent:
- C:\CODE\main.nut
Setting:
  device: 1
  fontname: Courier New
  fontsize: 10
  iconsize: 16
  mode: 0
  styleindex: 8
  tabwidth: 4
  thresh: 2
  workspace: C:/CODE/
Style: 0
TODO:
- Remove Headers
- Rewrite code
