ADB:
- C:/CODE/main.nut /sdcard/
- com.emo_framework.examples/com.emo_framework.EmoActivity
- EmoFramework
- com.emo_framework.examples
ANT:
- android update project --target 5 --path .
- ant debug install
CMD:
- ADD
- GCC
- CMD
- PYTHON
- ADB
- G++
- Make
- Sq
File:
- C:/CODE/assets/common.nut
- C:/CODE/assets/creditscene.nut
- C:/CODE/assets/logoscene.nut
- C:/CODE/assets/howtoscene.nut
Project:
- C:/CODE/data/
- C:/CODE/assets/
Recent:
- C:\CODE\main.nut
Setting:
  device: 1
  fontname: Courier New
  fontsize: 10
  iconsize: 16
  styleindex: 8
  thresh: 1
  workspace: C:/CODE/
Style: 0
