ADB:
- C:/Android-Template/assets/main.nut /sdcard/
- com.emo_framework.examples/com.emo_framework.EmoActivity
- EmoFramework
- com.emo_framework.examples
ANT:
- android.bat update project -p
- ant.bat debug -buildfile
- ant.bat installd -buildfile
- ant.bat debug install -buildfile
- ant.bat clean -buildfile
CMD:
- CMD
- PYTHON
- ADB
- G++
- Make
- SQ
- JAVA
- GCC
ClosedProject:
- 0
- 0
- 0
- 0
File:
- C:/CODE/assets/common.nut
- C:/CODE/assets/creditscene.nut
- C:/CODE/assets/logoscene.nut
PARAM:
- Dude C:/CODE/assets/creditscene.nut C:/CODE/assets/physics.nut
Project:
- C:/CODE/assets/
Recent: []
Setting:
  device: 1
  encoding: 1
  fontname: Courier New
  fontsize: 10
  iconsize: 16
  indent: 0
  margin: 1
  mode: 0
  styleindex: 8
  tabwidth: 4
  thresh: 1
  toollabel: 0
  whitespace: 1
  workspace: C:/CODE/
Style: 0
TODO:
- Fix Closed Projects Bug
- Add Build Options
- Add OS support
- Add Style Options
- Add iOS support
- Make Mac Build
- Dude
