File:
- C:/CODE/assets/main.nut
- C:/CODE/assets/physics.nut
- C:/CODE/assets/titlescene.nut
Project:
- C:/CODE/assets/
- C:/CODE/data/
Recent:
- C:\CODE\IDE\main.nut
Setting:
  fontname: Courier
  fontsize: 10
  iconsize: 16
  workspace: C:/CODE
