File:
- C:\CODE\IDE\main.nut
- C:\CODE\assets\main.nut
Project:
- C:\CODE\assets\
- C:\CODE\IDE\
- !!python/unicode 'C:/CODE/Icons'
Recent:
- C:\CODE\IDE\main.nut
Setting:
  fontname: Courier
  fontsize: 10
  iconsize: 16
  workspace: C:/CODE
