ADB:
- C:/Android-Template/assets/main.nut /sdcard/
- com.emo_framework.examples/com.emo_framework.EmoActivity
- EmoFramework
- com.emo_framework.examples
ANT:
- android.bat update project -p
- ant.bat debug -buildfile
- ant.bat installd -buildfile
- ant.bat debug install -buildfile
- ant.bat clean -buildfile
CMD:
- CMD
- PYTHON
- ADB
- G++
- Make
- SQ
- JAVA
- GCC
- MOON
ClosedProject:
- 0
File:
- C:/CODE/assets/common.nut
- C:/gg.moon
- C:/CODE/assets/Engine.h
- C:/CODE/assets/howtoscene.nut
- C:/CODE/assets/titlescene.nut
PARAM:
- Dude C:/CODE/assets/creditscene.nut C:/CODE/assets/physics.nut
- C:/gg.moon
- ' C:/gg.moon'
Project:
- C:/CODE/assets/
Recent: []
Setting:
  api: emo
  device: 1
  encoding: 1
  fontname: Courier New
  fontsize: 10
  hide: 1
  iconsize: 16
  indent: 0
  margin: 1
  mode: 1
  tabwidth: 4
  thresh: 1
  toollabel: 0
  whitespace: 0
  workspace: C:/CODE/
Style:
  back: '#ffffff'
  base: '#ff030f'
  caret: '#e8f2fe'
  comment: '#3f7f5f'
  keyword: '#7f0055'
  margin: '#ece9d8'
  marker: '#ee1111'
  number: '#0e8bff'
  operator: '#000000'
  string: '#7f0010'
TODO:
- Add OS support
- Add iOS support
- Make Mac Build
- Add AutoHide
- Must implement Lexer
