ADB:
- C:/CODE/sabel.png /sdcard/
- com.emo_framework.examples/com.emo_framework.EmoActivity
- EmoFramework
- com.emo_framework.examples
ANT:
- android update project --target 5 --path .
- ant debug install
CMD:
- GCC
- CMD
- PYTHON
- ADB
- G++
- Make
- SQ
- JAVA
ClosedProject:
- 0
- 0
- 0
File:
- C:/CODE/assetsd/creditscene.nut
- C:/CODE/assetsd/common.nut
- C:/CODE/assetsd/common.nut
- C:/CODE/assetsd/howtoscene.nut
PARAM:
- hh C:/CODE/152940-ios.jpeg
Project:
- C:/CODE/datad/
- C:/CODE/assetsd/
Recent: []
Setting:
  device: 1
  fontname: Courier New
  fontsize: 10
  iconsize: 16
  mode: 0
  styleindex: 8
  tabwidth: 4
  thresh: 2
  workspace: C:/CODE/
Style: 0
TODO:
- Fix Closed Projects Bug
- Add Build Options
- Add OS support
