ADB:
- adb -d push C:/CODE/main.nut /sdcard/
- adb -d shell am start -a android.intent.action.MAIN -n com.emo_framework.examples/com.emo_framework.EmoActivity
- adb -d logcat -s EmoFramework
- adb -d shell ps | grep com.emo_framework.examples | awk '{print $2}' | xargs adb
  shell kill
File:
- C:/CODE/assets/main.nut
Project:
- C:/CODE/assets/
Recent:
- C:\CODE\IDE\main.nut
Setting:
  fontname: Courier
  fontsize: 10
  iconsize: 16
  workspace: C:/CODE/
