ADB:
- adb -d push C:/CODE/main.nut /sdcard/
- adb -d shell am start -a android.intent.action.MAIN -n com.emo_framework.examples/com.emo_framework.EmoActivity
- adb -d logcat -s EmoFramework
- adb -d shell ps | grep com.emo_framework.examples | awk '{print $2}' | xargs adb
  shell kill
File:
- C:/CODE/assetsdd/creditscene.nut
- C:/CODE/assetsdd/howtoscene.nut
Project:
- C:/CODE/data/
- C:/CODE/assetsdd/
Recent:
- C:\CODE\main.nut
Setting:
  fontname: Courier
  fontsize: 10
  iconsize: 16
  style: 0
  thresh: 1
  workspace: C:/CODE/
Styles:
  default:
    bg: white
    color: black
