ADB:
- adb -d push C:/CODE/main.nut /sdcard/
- adb -d shell am start -a android.intent.action.MAIN -n com.emo_framework.examples/com.emo_framework.EmoActivity
- adb -d logcat -s EmoFramework
- adb -d shell ps | grep com.emo_framework.examples | awk '{print $2}' | xargs adb
  shell kill
File:
- C:/CODE/assets/runtime.nut
- C:/CODE/assets/main.nut
- C:/CODE/assets/howtoscene.nut
Project:
- C:/CODE/data/
- C:/CODE/assets/
Recent:
- C:\CODE\main.nut
Setting:
  fontname: Courier New
  fontsize: 10
  iconsize: 16
  styleindex: 4
  thresh: 1
  workspace: C:/CODE/
Style: 0
